### ISSUE TITLE
Doesn't scale too well on mobile apps.

### ISSUE THREAD

**Issue by justin13888** [hamedbaatour/minimus#1]
Sorry that I can't show any pictures. Also I know that this app still extra new.

**Comment by markgoho-EDT** [comment]
"production ready" is a bit misleading

**Comment by hamedbaatour** [comment]
@justin13888 I am aware that it is not responsive yet! I always add media queries when the desktop view is completely done because I don't want to modify the CSS twice when I want to change something in the design (desktop view CSS and down in the media queries). I am going to close this issue for now.
 @markgoho-EDT dude it is still part I of the tutorial series so relax.
